version: 0.1

phases:
  install:
    commands:
        - echo Nothing to do in the install phase...
  pre_build:
    commands:
        - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - root/./gradlew --debug --stacktrace build
      - root/./gradlew assemble
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - test.apk
  discard-paths: yes
